version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.13.3
  - 0.27.0-RC1

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh
