version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 3.0.0
  - 2.13.6

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11
  - ADOPTOPENJDK=17

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh
